# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ralampay/workspace/object-detector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ralampay/workspace/object-detector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ralampay/workspace/object-detector/CMakeFiles /home/ralampay/workspace/object-detector/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ralampay/workspace/object-detector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named edge-detector

# Build rule for target.
edge-detector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edge-detector
.PHONY : edge-detector

# fast build rule for target.
edge-detector/fast:
	$(MAKE) -f CMakeFiles/edge-detector.dir/build.make CMakeFiles/edge-detector.dir/build
.PHONY : edge-detector/fast

src/edge-detector.o: src/edge-detector.cpp.o

.PHONY : src/edge-detector.o

# target to build an object file
src/edge-detector.cpp.o:
	$(MAKE) -f CMakeFiles/edge-detector.dir/build.make CMakeFiles/edge-detector.dir/src/edge-detector.cpp.o
.PHONY : src/edge-detector.cpp.o

src/edge-detector.i: src/edge-detector.cpp.i

.PHONY : src/edge-detector.i

# target to preprocess a source file
src/edge-detector.cpp.i:
	$(MAKE) -f CMakeFiles/edge-detector.dir/build.make CMakeFiles/edge-detector.dir/src/edge-detector.cpp.i
.PHONY : src/edge-detector.cpp.i

src/edge-detector.s: src/edge-detector.cpp.s

.PHONY : src/edge-detector.s

# target to generate assembly for a file
src/edge-detector.cpp.s:
	$(MAKE) -f CMakeFiles/edge-detector.dir/build.make CMakeFiles/edge-detector.dir/src/edge-detector.cpp.s
.PHONY : src/edge-detector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... edge-detector"
	@echo "... src/edge-detector.o"
	@echo "... src/edge-detector.i"
	@echo "... src/edge-detector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

